highlighter: rouge
markdown: kramdown
author: Jujhar Singh
url: https://devsecopscm.jujhar.com
permalink: pretty
exclude: ['README.md','_config.yaml','.gitignore','/.git','.history']
timezone: Europe/London

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [production]

custom_variable: "custom value"
analytics-id: "UA-173027048-1"
